### ISSUE TITLE
Remove Wav file names on Editor

### ISSUE THREAD

**Issue by luisArandas** [ReaTeam/ReaScripts#132]
Is possible to remove the wav file names from the wav files in the Reaper editor?
Or put it inside it?
The wav item is not the height of the track because of the file name.
Best, Luis

**Comment by cfillion** [comment]
There's options for both disabling the label or putting it inside the item in Preferences > Appearance > Media.

![Screenshot](https://i.imgur.com/tRNG6Qa.png)

This is the bug tracker for the ReaTeam script release repository. Unrelated REAPER usage question should be asked on the [Cockos forum](http://forum.cockos.com/).

**Comment by luisArandas** [comment]
Thank you very much cfillion. I appreciate the fast response.
