### ISSUE TITLE
[FR] Provide option to set the MIDI bus in GUI

### ISSUE THREAD

**Issue by daeavelwyn** [ReaTeam/ReaScripts#193]
Hello,

Could you please provide an option that could let us define the MIDI Bus we want ?

thks

**Comment by cfillion** [comment]
Is this a request for a new script, or for editing an existing one (if so, which one)?

Do you mean a VST3 input or output MIDI bus, or track routing MIDI bus?

**Comment by daeavelwyn** [comment]
Hi cfillion,

Sorry just realize I'm not sure this is the right place to post this FR. I'm talking about "Script: js_Autoincrement MIDI send channels of selected tracks.lua", an option to either add VST3's input / output MIDI bus or routing MIDI bus could improve my workflow.

Here is an example:

```
Woodwinds (root folder with Vienna Ensemble pro vsti3 plugin)
        |
        ----Flute 1 (send to MIDI chan 1 bus 1 --> B1/1)
        ----Flute 2 (send to MIDI chan 2 bus 1 --> B1/2)
        ----Oboe 1 (send to MIDI chan 3 bus 1 --> B1/3)
        ----Oboe 2 (send to MIDI chan 4 bus 1 --> B1/4)
        ----Clar 1 (send to MIDI chan 5 bus 1 --> B1/5)
        ----etc...
Brasss (root folder with Vienna Ensemble pro vsti3 plugin)
        |
        ----Horn 1 (send to MIDI chan 1 bus 2 --> B2/1)
        ----Horn 2 (send to MIDI chan 2 bus 2 --> B2/2)
        ----Trumpet 1 (send to MIDI chan 3 bus 2 --> B2/3)
        ----Trumpet 2 (send to MIDI chan 4 bus 2 --> B2/4)
        ----Trombone 1 (send to MIDI chan 5 bus 2 --> B2/5)
        ----etc...
```
As you can see, having the ability to create bus from the script could help to improve templates creation.

**Comment by X-Raym** [comment]
@daeavelwyn Hi, if this is stilll needed, maybe contact @juliansader directly on the forum. Cheers!
