### ISSUE TITLE
Submitting hosted files via ReaPack panel

### ISSUE THREAD

**Issue by Buy-One** [ReaTeam/ReaScripts#595]
I get the following error message despite following the [video tutorial](https://github.com/ReaTeam/ReaScripts/pull/582#issuecomment-748501874) of submitting hosted files as per @cfillion [suggestion](https://github.com/ReaTeam/ReaScripts/pull/587#issuecomment-753524619):

> Please correct the following error(s):
> 'Various/buyone_Convert custom actions to Lua ReaScript.lua' is unused (not installed and not used as source for another file).

The main package file under which come the hosted ones is unchecked and set to 'Don't install', the **metapackage** tag is there

![sceenshot](https://user-images.githubusercontent.com/61803004/103477109-05baf780-4dc4-11eb-9b6a-9f698caa7595.png)

**Comment by cfillion** [comment]
Thanks, looks like a bug in the validation code that rejects metapackage files that are not used as source for another file. Fixing! (for future reference, bug reports for the GUI editor belong at [cfillion/reapack.com](https://github.com/cfillion/reapack.com))

Another way, that bypasses the issue, would be to put the main script's content in the package file (resource type = Script) and only create two Hosted files for the other scripts. This would avoid having two identically-named "buyone_Convert custom actions to Lua ReaScript.lua" files.
