### ISSUE TITLE
Metatag to install script in several Action list sections at once

### ISSUE THREAD

**Issue by Buy-One** [ReaTeam/ReaScripts#742]
From the Wiki

> main=comma-separated,list : Set in which section(s) the script should be registered in. Possible values are  main ,  midi_editor ,  midi_inlineeditor ,  midi_eventlisteditor  and mediaexplorer .

But it seems to be mentioned in the context of metapackages. How should it be handled in a single script?

**Comment by cfillion** [comment]
The `@provides` tag can customize all files provided into the package, including the current file (either using its filename, or `.` as a shortcut).

As seen in the package editor:
![screencap](https://i.imgur.com/KMpLfUJ.gif)

**Comment by Buy-One** [comment]
Thank you Christian
