### ISSUE TITLE
Pooled automation items works only on main envelopes 

### ISSUE THREAD

**Issue by ccazerty** [ReaTeam/ReaScripts#753]
It is about the following script :

"amagalma_Insert pooled instances of one automation item in time selection for selected tracks and selected envelope.lua"

this script seems to work only on main envelopes, like volume, pan, etc. But not on fx parameters envelopes (eq, reacontrolMidi, etc.)

**Comment by cfillion** [comment]
This is a release repository. Best to contact the developer of that script (@amagalma) directly to report any issues.

https://forum.cockos.com/member.php?u=32436
