### ISSUE TITLE
Error when trying to insert an FX

### ISSUE THREAD

**Issue by rivella50** [ReaTeam/ReaScripts#776]
Hi there,
i just tried the script 'Insert selected FX or FX chain...' and always get this error: No FX have been selected in the FX Browser.
The steps i performed are as instructed: Select a plugin in the FX Browser, then select 1-n tracks and choose the action or the shortcut i created for it.
Copying a plugin from a track's FX chain to other track chains works fine btw.
I use Reaper 5.99
Thanks for your assistance.

**Comment by Buy-One** [comment]
Hi

Apologies for the belated response, didn't expect to see here any report on issues with my script. After a short investigation i discovered that the specific function which allows selecting FX in the FX browser and adding to objects had been introduced in the build 6.12c. **Therefore i'm afraid it won't work in earlier builds.** 

From 6.12c change log

> ReaScript: update Track/TakeFX_AddByName() to allow inserting FXADD:, allow inserting FX at position in chain

http://reaper.fm/download-old.php?ver=6x

So i apologize for the misleading info of the script requiring at least REAPER v5.962, it has been updated and incompatibility error proofing has been implemented. Before the update is merged with the Master the new version can be downloaded [here](https://raw.githubusercontent.com/ReaTeam/ReaScripts/cd8aa16a11804d08c5d34fcc4fdc18344678650c/FX/BuyOne_Insert%20selected%20FX%20or%20FX%20chain%20presets%20in%20OR%20copy%20focused%20FX%20to%20selected%20objects.lua)

**Comment by rivella50** [comment]
Thanks for your answer. Sooner or later i will upgrade to Reaper 6 for sure, then i can consume that function too.
