### ISSUE TITLE
I'm trying to get my repo to play nice

### ISSUE THREAD

**Issue by JoepVanlier** [ReaTeam/ReaScripts#88]
I would like to make my repository compatible with ReaPack. I've read the tutorials on: 
https://github.com/cfillion/reapack-index/wiki#filling-the-about-section and https://www.extremraym.com/en/reapack/

I've managed to add my repo to my local ReaPack after generating the index.xml in the repo and adding https://github.com/joepvanlier/Hackey-Trackey/raw/master/index.xml to my repo list in ReaPack. However, the about section doesn't show up despite calling --about=README.md on reapack-index. 

E:\ReaperDev\Hackey-Trackey>reapack-index --about=README.md
Indexing commit 1 of 1 (100%)...
1 modified metadata
Commit the new index? [y/N] y
commit created

Am I doing something wrong?

**Comment by cfillion** [comment]
It works here (eg. by double clicking on Tracker tools in Manage repositories). Try refreshing the index cache by either synchronizing or right click on Tracker tools in Manage repositories > Refresh. If you are using ReaPack on Linux (beta), the rich text documentation display is not implemented yet.

(This is the issue tracker of the ReaTeam script repository. You are welcome to upload your script for release here: reapack-index is run automatically for you and the repo is enabled by default for all users.)

**Comment by JoepVanlier** [comment]
Hmm. Ah sorry, yes. It seems to have ended up somewhere. I just noticed that if I click "About tracker tools" that I get the description now. How would I go about adding a description for the package? Since that's the first thing a user would see, it'd be nice to have some text there. It also seems my markdown table isn't working for some reason, but I can replace that with something else.

I think it'd be awesome if it could be added, but I'm still pretty actively developing it. How would I go about updating it later if it were part of the ReaTeam repo? Via pull requests?

**Comment by cfillion** [comment]
Package documentation is done with the [`@about`](https://github.com/cfillion/reapack-index/wiki/Packaging-Documentation#about) tag in the package's header.

https://github.com/cfillion/reapack-index/wiki/Packaging-Documentation

> How would I go about updating it later if it were part of the ReaTeam repo? Via pull requests?

Yes, when you have a new version (stable or beta) ready for release. You can use the "Create new file"  and edit buttons in the GitHub interface for this, or fork this repository and make branches with your changes locally.

**Comment by JoepVanlier** [comment]
Thanks! I was confused by the different formats I was seeing in the various script files. It works now! 👍 

Sounds good. Any rules as to where I should place it? It's kind of like a MIDI/Automation editor. I would only describe it as tracker, but I imagine you want to keep the number of categories low :)

**Comment by cfillion** [comment]
I think "MIDI" would be a good (new) category for this. It's already used in the JSFX repo, and also in X-Raym's and MPL's ones for non-MIDI Editor but still MIDI-related packages.

(cc @X-Raym)

**Comment by X-Raym** [comment]
Closed cause it seems resolved.
